# Generated by Django 4.2.6 on 2023-12-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subhan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=200, null=True, verbose_name='No Transaksi')),
                ('nama_depan', models.CharField(max_length=200, null=True, verbose_name='Nama Depan')),
                ('nama_belakang', models.CharField(max_length=200, null=True, verbose_name='Nama Belakang')),
                ('alamat', models.TextField(max_length=200, null=True, verbose_name='Alamat')),
                ('provinsi', models.CharField(max_length=200, null=True, verbose_name='Provinsi')),
                ('kabupaten', models.CharField(max_length=200, null=True, verbose_name='Kabupaten')),
                ('kecamatan', models.CharField(max_length=200, null=True, verbose_name='Kecamatan')),
                ('kode_post', models.CharField(max_length=200, null=True, verbose_name='Kode Pos')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('whatsapp', models.CharField(max_length=200, null=True, verbose_name='No WhatsApp')),
                ('total_transaksi', models.BigIntegerField(blank=True, null=True, verbose_name='Total Transaksi')),
                ('status', models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Lunas', 'Lunas')], default='Baru', max_length=200, null=True, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tanggal Dibuat')),
                ('tanggal_kirim', models.DateTimeField(null=True, verbose_name='Tanggal Kirim')),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=200, null=True, verbose_name='No Transaksi')),
                ('jumlah', models.IntegerField(blank=True, null=True, verbose_name='Jumlah')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subhan.produk')),
            ],
            options={
                'verbose_name_plural': 'Detail Transaksi',
            },
        ),
    ]
